# fly.toml app configuration file generated for web-broken-lake-5252 on 2024-07-11T21:06:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-broken-lake-5252'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 512

[env]
  PAGE_URL = 'https://web-broken-lake-5252.fly.dev'
  API_URL = 'https://api-blue-dream-2825.fly.dev'
  PORT = '3000'