# fly.toml app configuration file generated for fly-redis-purple-darkness-8493 on 2024-08-18T15:48:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-redis-purple-darkness-8493'
primary_region = 'waw'

[build]
  image = 'flyio/redis:6.2.6'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  destination = "/data"
  source = "redis_server"