# fly.toml app configuration file generated for api-blue-dream-2825 on 2024-07-11T20:20:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-blue-dream-2825'
primary_region = 'waw'
swap_size_mb = 256

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 512

[env]
  REDIS_URL = 'redis://fly-redis-purple-darkness-8493.internal:6379'
  REDIS_TTL = '60000'