name: Api Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'apps/api/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: '9'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'apps/api/pnpm-lock.yaml'
      - run: pnpm install
      - run: pnpm run lint
      - name: Start container
        run: docker compose -p budget-tracker -f .docker/docker-compose-dependencies.yml up -d --build --remove-orphans
      - run: pnpm run test:e2e
      - name: Stop container
        run: docker compose -p budget-tracker -f .docker/docker-compose-dependencies.yml down
      - run: pnpm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}