name: Web Release
on:
  release:
    types:
      - created
defaults:
  run:
    working-directory: apps/web

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web:latest
          labels: |
            org.opencontainers.image.title=web
            org.opencontainers.image.description=web
            org.opencontainers.image.source=