version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 54321:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    container_name: cache
    image: redis
    ports:
      - 63798:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
